spring:
  application:
    name: Progress Tracker

  datasource:
    url: jdbc:postgresql://localhost:5432/progresstracker
    username: ptrack
    password: ptrack

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

queue:
  enabled: true
  awsRegion: us-west-1
  sqsUrl: "https://sqs.us-west-1.amazonaws.com/648093549515/progresstracker-completions"

