-- The schema as both services created it with Hibernate's ddl-auto=update, before migrations.
-- From here on the API applies every schema change as a new versioned file in this folder, and
-- both services only validate their entities against the result (ddl-auto=validate).
-- Constraint names are the ones Hibernate generated, so this matches databases it created.

create table app_user (
    id            bigint generated by default as identity primary key,
    email         varchar(255) not null,
    password_hash varchar(255) not null,
    constraint uk1j9d9a06i600gd43uu3km82jw unique (email)
);

create table achievement (
    id          bigint generated by default as identity primary key,
    code        varchar(255) not null,
    description varchar(255) not null,
    name        varchar(255) not null,
    threshold   integer      not null,
    type        varchar(255) not null,
    constraint ukp5u28lxg7ygmermogrkwpolqw unique (code)
);

-- The API writes name, description and goal; the worker writes XP and streak columns.
create table habit (
    id                  bigint generated by default as identity primary key,
    created_at          timestamp(6),
    current_streak      integer not null,
    description         varchar(255),
    frequency           varchar(255),
    goal_period         varchar(255),
    goal_target_count   integer,
    last_completed_date date,
    longest_streak      integer not null,
    name                varchar(255),
    xp_total            integer not null,
    user_id             bigint,
    constraint habit_frequency_check check (frequency in ('DAILY', 'WEEKLY')),
    constraint habit_goal_period_check check (goal_period in ('DAILY', 'WEEKLY')),
    constraint fk67p5axvkae90eone6kmlhesoa foreign key (user_id) references app_user (id)
);
create index idx_habit_user_id on habit (user_id);

-- One row per completed day; the unique key is what makes a day count once.
create table habit_entries (
    id             bigint generated by default as identity primary key,
    completed_date date                        not null,
    created_at     timestamp(6) with time zone not null,
    xp_earned      integer                     not null,
    habit_id       bigint                      not null,
    constraint ukgw7mbwrhgpncup7rs4yplnpha unique (habit_id, completed_date),
    constraint fk7s6djyfu91ydg7nfwy13v891g foreign key (habit_id) references habit (id)
);

create table user_achievement (
    id             bigint generated by default as identity primary key,
    unlocked_at    timestamp(6),
    achievement_id bigint not null,
    user_id        bigint not null,
    constraint ukmq7dserbfaub7gw4f7n158oe5 unique (user_id, achievement_id),
    constraint fkcxeo6malce3dsw6tc43bcrwfd foreign key (achievement_id) references achievement (id),
    constraint fkesc2lk51gdxbv7x491q9ftowv foreign key (user_id) references app_user (id)
);

-- Transactional outbox (API): written with each completion, published to SQS by the relay.
create table outbox_events (
    id           uuid                        not null primary key,
    created_at   timestamp(6) with time zone not null,
    payload      text                        not null,
    published_at timestamp(6) with time zone,
    type         varchar(100)                not null
);
create index idx_outbox_events_unpublished on outbox_events (published_at, created_at);

-- Idempotent consumer (worker): one row per event already handled.
create table processed_events (
    event_id     uuid                        not null primary key,
    occurred_at  timestamp(6) with time zone,
    processed_at timestamp(6) with time zone not null
);

-- Weekly summaries: requested by the API, claimed and written by the worker.
create table weekly_summaries (
    id              bigint generated by default as identity primary key,
    attempts        integer                     not null,
    body            varchar(600),
    completed_at    timestamp(6) with time zone,
    completions     integer,
    created_at      timestamp(6) with time zone not null,
    fallback_reason varchar(300),
    focus_habit     varchar(255),
    headline        varchar(120),
    input_tokens    integer,
    last_error      varchar(300),
    latency_ms      integer,
    lease_until     timestamp(6) with time zone,
    model           varchar(100),
    output_tokens   integer,
    source          varchar(20),
    status          varchar(20)                 not null,
    week_start      date                        not null,
    xp_earned       integer,
    user_id         bigint                      not null,
    constraint weekly_summaries_source_check check (source in ('AI', 'TEMPLATE')),
    constraint weekly_summaries_status_check check (status in ('PENDING', 'IN_PROGRESS', 'READY', 'FAILED')),
    constraint uk_weekly_summaries_user_week unique (user_id, week_start),
    constraint fkfu9ejati7bvklpgurqsgkn8ns foreign key (user_id) references app_user (id)
);
create index idx_weekly_summaries_status on weekly_summaries (status, created_at);
create index idx_weekly_summaries_completed_at on weekly_summaries (completed_at);

-- Daily caps on LLM calls (worker), reserved before each call.
create table llm_daily_usage (
    usage_date      date    not null primary key,
    calls           integer not null,
    reserved_tokens bigint  not null
);
